name: Test project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
      # uses: para acciones del store de gitHub
      # run: para crear acciones
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        # npm ci: es como npm install pero se asegura que se instale las mimas visiones usadas en desarrollo en el package.json
        run: npm ci
      - name: Run test
        run: npm test
